Description: >
  Mubarak Imam / Udacity Nanodegree Project 2 - Udagram Clone
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  AMIToUse:
    Type: String
    Default: 'ami-08fdec01f5df9998f'
    Description: 'ami to use for EC2 resources'
  JumpServerKeyName:
    Description: The name of a pre-existing key-pair to use in accessing the jump server
    Type: String
  SourceIP:
    Description: Ip address to allow SSH access to the jump server
    Type: String
    Default: 105.113.20.50/32

Resources:
  JumpServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to private servers via Jump servers
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Sub ${SourceIP}
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0

  JumpServerIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'

  JumpServerIamPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: fullAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      Roles:
        - !Ref JumpServerIamRole

  JumpServerIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref JumpServerIamRole

  UdagramJumpBox:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref AMIToUse
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          cd /home/ubuntu
          aws s3 cp s3://${KeyPairBucketName}/${WebServersKeyPair}.pem /home/ubuntu
          chmod 400 ${WebServersKeyPair}.pem
      IamInstanceProfile: !Ref JumpServerIamInstanceProfile
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet: 
            - Ref: JumpServerSecGroup
          SubnetId:
            Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN
      Tags:
      - Key: Name
        Value: Jumpbox
      KeyName: !Ref JumpServerKeyName

Outputs:
  JumpServerIp:
    Description: A reference to the jump server public IP
    Value: !GetAtt UdagramJumpBox.PublicIp
    Export:
      Name: !Sub ${EnvironmentName}-JUMP-IP
